version: '3.7'

services:
  minigames-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    container_name: minigames-backend
    expose:
      - '4000'
    ports:
      - '4000:4000'

  minigames-frontend:
    build:
      context: ./game
      dockerfile: Dockerfile.dev
    container_name: minigames-frontend
    expose:
      - '4000'
    ports:
      - '4000:4000'